/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * The URL to the generic Mollie API error handling guide.
 */
export type DisableMethodDocumentation = {
  href?: any | undefined;
  type?: any | undefined;
};

export type DisableMethodLinks = {
  /**
   * The URL to the generic Mollie API error handling guide.
   */
  documentation?: DisableMethodDocumentation | undefined;
};

/**
 * An error response object.
 */
export type DisableMethodResponseBodyData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: DisableMethodLinks | undefined;
};

/**
 * An error response object.
 */
export class DisableMethodResponseBody extends Error {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: DisableMethodLinks | undefined;

  /** The original data that was passed to this error instance. */
  data$: DisableMethodResponseBodyData;

  constructor(err: DisableMethodResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.status != null) this.status = err.status;
    if (err.title != null) this.title = err.title;
    if (err.detail != null) this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    if (err.links != null) this.links = err.links;

    this.name = "DisableMethodResponseBody";
  }
}

/** @internal */
export const DisableMethodDocumentation$inboundSchema: z.ZodType<
  DisableMethodDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.any(),
  type: z.any(),
});

/** @internal */
export type DisableMethodDocumentation$Outbound = {
  href?: any;
  type?: any;
};

/** @internal */
export const DisableMethodDocumentation$outboundSchema: z.ZodType<
  DisableMethodDocumentation$Outbound,
  z.ZodTypeDef,
  DisableMethodDocumentation
> = z.object({
  href: z.any(),
  type: z.any(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DisableMethodDocumentation$ {
  /** @deprecated use `DisableMethodDocumentation$inboundSchema` instead. */
  export const inboundSchema = DisableMethodDocumentation$inboundSchema;
  /** @deprecated use `DisableMethodDocumentation$outboundSchema` instead. */
  export const outboundSchema = DisableMethodDocumentation$outboundSchema;
  /** @deprecated use `DisableMethodDocumentation$Outbound` instead. */
  export type Outbound = DisableMethodDocumentation$Outbound;
}

/** @internal */
export const DisableMethodLinks$inboundSchema: z.ZodType<
  DisableMethodLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  documentation: z.lazy(() => DisableMethodDocumentation$inboundSchema)
    .optional(),
});

/** @internal */
export type DisableMethodLinks$Outbound = {
  documentation?: DisableMethodDocumentation$Outbound | undefined;
};

/** @internal */
export const DisableMethodLinks$outboundSchema: z.ZodType<
  DisableMethodLinks$Outbound,
  z.ZodTypeDef,
  DisableMethodLinks
> = z.object({
  documentation: z.lazy(() => DisableMethodDocumentation$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DisableMethodLinks$ {
  /** @deprecated use `DisableMethodLinks$inboundSchema` instead. */
  export const inboundSchema = DisableMethodLinks$inboundSchema;
  /** @deprecated use `DisableMethodLinks$outboundSchema` instead. */
  export const outboundSchema = DisableMethodLinks$outboundSchema;
  /** @deprecated use `DisableMethodLinks$Outbound` instead. */
  export type Outbound = DisableMethodLinks$Outbound;
}

/** @internal */
export const DisableMethodResponseBody$inboundSchema: z.ZodType<
  DisableMethodResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
  field: z.nullable(z.string()).optional(),
  _links: z.lazy(() => DisableMethodLinks$inboundSchema).optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new DisableMethodResponseBody(remapped);
  });

/** @internal */
export type DisableMethodResponseBody$Outbound = {
  status?: number | undefined;
  title?: string | undefined;
  detail?: string | undefined;
  field?: string | null | undefined;
  _links?: DisableMethodLinks$Outbound | undefined;
};

/** @internal */
export const DisableMethodResponseBody$outboundSchema: z.ZodType<
  DisableMethodResponseBody$Outbound,
  z.ZodTypeDef,
  DisableMethodResponseBody
> = z.instanceof(DisableMethodResponseBody)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int().optional(),
      title: z.string().optional(),
      detail: z.string().optional(),
      field: z.nullable(z.string()).optional(),
      links: z.lazy(() => DisableMethodLinks$outboundSchema).optional(),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DisableMethodResponseBody$ {
  /** @deprecated use `DisableMethodResponseBody$inboundSchema` instead. */
  export const inboundSchema = DisableMethodResponseBody$inboundSchema;
  /** @deprecated use `DisableMethodResponseBody$outboundSchema` instead. */
  export const outboundSchema = DisableMethodResponseBody$outboundSchema;
  /** @deprecated use `DisableMethodResponseBody$Outbound` instead. */
  export type Outbound = DisableMethodResponseBody$Outbound;
}
