/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * The URL to the generic Mollie API error handling guide.
 */
export type EnableMethodDocumentation = {
  href?: any | undefined;
  type?: any | undefined;
};

export type EnableMethodLinks = {
  /**
   * The URL to the generic Mollie API error handling guide.
   */
  documentation?: EnableMethodDocumentation | undefined;
};

/**
 * An error response object.
 */
export type EnableMethodResponseBodyData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: EnableMethodLinks | undefined;
};

/**
 * An error response object.
 */
export class EnableMethodResponseBody extends Error {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: EnableMethodLinks | undefined;

  /** The original data that was passed to this error instance. */
  data$: EnableMethodResponseBodyData;

  constructor(err: EnableMethodResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.status != null) this.status = err.status;
    if (err.title != null) this.title = err.title;
    if (err.detail != null) this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    if (err.links != null) this.links = err.links;

    this.name = "EnableMethodResponseBody";
  }
}

/** @internal */
export const EnableMethodDocumentation$inboundSchema: z.ZodType<
  EnableMethodDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.any(),
  type: z.any(),
});

/** @internal */
export type EnableMethodDocumentation$Outbound = {
  href?: any;
  type?: any;
};

/** @internal */
export const EnableMethodDocumentation$outboundSchema: z.ZodType<
  EnableMethodDocumentation$Outbound,
  z.ZodTypeDef,
  EnableMethodDocumentation
> = z.object({
  href: z.any(),
  type: z.any(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EnableMethodDocumentation$ {
  /** @deprecated use `EnableMethodDocumentation$inboundSchema` instead. */
  export const inboundSchema = EnableMethodDocumentation$inboundSchema;
  /** @deprecated use `EnableMethodDocumentation$outboundSchema` instead. */
  export const outboundSchema = EnableMethodDocumentation$outboundSchema;
  /** @deprecated use `EnableMethodDocumentation$Outbound` instead. */
  export type Outbound = EnableMethodDocumentation$Outbound;
}

/** @internal */
export const EnableMethodLinks$inboundSchema: z.ZodType<
  EnableMethodLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  documentation: z.lazy(() => EnableMethodDocumentation$inboundSchema)
    .optional(),
});

/** @internal */
export type EnableMethodLinks$Outbound = {
  documentation?: EnableMethodDocumentation$Outbound | undefined;
};

/** @internal */
export const EnableMethodLinks$outboundSchema: z.ZodType<
  EnableMethodLinks$Outbound,
  z.ZodTypeDef,
  EnableMethodLinks
> = z.object({
  documentation: z.lazy(() => EnableMethodDocumentation$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EnableMethodLinks$ {
  /** @deprecated use `EnableMethodLinks$inboundSchema` instead. */
  export const inboundSchema = EnableMethodLinks$inboundSchema;
  /** @deprecated use `EnableMethodLinks$outboundSchema` instead. */
  export const outboundSchema = EnableMethodLinks$outboundSchema;
  /** @deprecated use `EnableMethodLinks$Outbound` instead. */
  export type Outbound = EnableMethodLinks$Outbound;
}

/** @internal */
export const EnableMethodResponseBody$inboundSchema: z.ZodType<
  EnableMethodResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
  field: z.nullable(z.string()).optional(),
  _links: z.lazy(() => EnableMethodLinks$inboundSchema).optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new EnableMethodResponseBody(remapped);
  });

/** @internal */
export type EnableMethodResponseBody$Outbound = {
  status?: number | undefined;
  title?: string | undefined;
  detail?: string | undefined;
  field?: string | null | undefined;
  _links?: EnableMethodLinks$Outbound | undefined;
};

/** @internal */
export const EnableMethodResponseBody$outboundSchema: z.ZodType<
  EnableMethodResponseBody$Outbound,
  z.ZodTypeDef,
  EnableMethodResponseBody
> = z.instanceof(EnableMethodResponseBody)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int().optional(),
      title: z.string().optional(),
      detail: z.string().optional(),
      field: z.nullable(z.string()).optional(),
      links: z.lazy(() => EnableMethodLinks$outboundSchema).optional(),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EnableMethodResponseBody$ {
  /** @deprecated use `EnableMethodResponseBody$inboundSchema` instead. */
  export const inboundSchema = EnableMethodResponseBody$inboundSchema;
  /** @deprecated use `EnableMethodResponseBody$outboundSchema` instead. */
  export const outboundSchema = EnableMethodResponseBody$outboundSchema;
  /** @deprecated use `EnableMethodResponseBody$Outbound` instead. */
  export type Outbound = EnableMethodResponseBody$Outbound;
}
