/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * The URL to the generic Mollie API error handling guide.
 */
export type GetCaptureDocumentation = {
  href?: any | undefined;
  type?: any | undefined;
};

export type GetCaptureLinks = {
  /**
   * The URL to the generic Mollie API error handling guide.
   */
  documentation?: GetCaptureDocumentation | undefined;
};

/**
 * An error response object.
 */
export type GetCaptureResponseBodyData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: GetCaptureLinks | undefined;
};

/**
 * An error response object.
 */
export class GetCaptureResponseBody extends Error {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: GetCaptureLinks | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetCaptureResponseBodyData;

  constructor(err: GetCaptureResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.status != null) this.status = err.status;
    if (err.title != null) this.title = err.title;
    if (err.detail != null) this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    if (err.links != null) this.links = err.links;

    this.name = "GetCaptureResponseBody";
  }
}

/** @internal */
export const GetCaptureDocumentation$inboundSchema: z.ZodType<
  GetCaptureDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.any(),
  type: z.any(),
});

/** @internal */
export type GetCaptureDocumentation$Outbound = {
  href?: any;
  type?: any;
};

/** @internal */
export const GetCaptureDocumentation$outboundSchema: z.ZodType<
  GetCaptureDocumentation$Outbound,
  z.ZodTypeDef,
  GetCaptureDocumentation
> = z.object({
  href: z.any(),
  type: z.any(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCaptureDocumentation$ {
  /** @deprecated use `GetCaptureDocumentation$inboundSchema` instead. */
  export const inboundSchema = GetCaptureDocumentation$inboundSchema;
  /** @deprecated use `GetCaptureDocumentation$outboundSchema` instead. */
  export const outboundSchema = GetCaptureDocumentation$outboundSchema;
  /** @deprecated use `GetCaptureDocumentation$Outbound` instead. */
  export type Outbound = GetCaptureDocumentation$Outbound;
}

/** @internal */
export const GetCaptureLinks$inboundSchema: z.ZodType<
  GetCaptureLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  documentation: z.lazy(() => GetCaptureDocumentation$inboundSchema).optional(),
});

/** @internal */
export type GetCaptureLinks$Outbound = {
  documentation?: GetCaptureDocumentation$Outbound | undefined;
};

/** @internal */
export const GetCaptureLinks$outboundSchema: z.ZodType<
  GetCaptureLinks$Outbound,
  z.ZodTypeDef,
  GetCaptureLinks
> = z.object({
  documentation: z.lazy(() => GetCaptureDocumentation$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCaptureLinks$ {
  /** @deprecated use `GetCaptureLinks$inboundSchema` instead. */
  export const inboundSchema = GetCaptureLinks$inboundSchema;
  /** @deprecated use `GetCaptureLinks$outboundSchema` instead. */
  export const outboundSchema = GetCaptureLinks$outboundSchema;
  /** @deprecated use `GetCaptureLinks$Outbound` instead. */
  export type Outbound = GetCaptureLinks$Outbound;
}

/** @internal */
export const GetCaptureResponseBody$inboundSchema: z.ZodType<
  GetCaptureResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
  field: z.nullable(z.string()).optional(),
  _links: z.lazy(() => GetCaptureLinks$inboundSchema).optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new GetCaptureResponseBody(remapped);
  });

/** @internal */
export type GetCaptureResponseBody$Outbound = {
  status?: number | undefined;
  title?: string | undefined;
  detail?: string | undefined;
  field?: string | null | undefined;
  _links?: GetCaptureLinks$Outbound | undefined;
};

/** @internal */
export const GetCaptureResponseBody$outboundSchema: z.ZodType<
  GetCaptureResponseBody$Outbound,
  z.ZodTypeDef,
  GetCaptureResponseBody
> = z.instanceof(GetCaptureResponseBody)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int().optional(),
      title: z.string().optional(),
      detail: z.string().optional(),
      field: z.nullable(z.string()).optional(),
      links: z.lazy(() => GetCaptureLinks$outboundSchema).optional(),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCaptureResponseBody$ {
  /** @deprecated use `GetCaptureResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetCaptureResponseBody$inboundSchema;
  /** @deprecated use `GetCaptureResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetCaptureResponseBody$outboundSchema;
  /** @deprecated use `GetCaptureResponseBody$Outbound` instead. */
  export type Outbound = GetCaptureResponseBody$Outbound;
}
