/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * The URL to the generic Mollie API error handling guide.
 */
export type GetChargebackDocumentation = {
  href?: any | undefined;
  type?: any | undefined;
};

export type GetChargebackLinks = {
  /**
   * The URL to the generic Mollie API error handling guide.
   */
  documentation?: GetChargebackDocumentation | undefined;
};

/**
 * An error response object.
 */
export type GetChargebackResponseBodyData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: GetChargebackLinks | undefined;
};

/**
 * An error response object.
 */
export class GetChargebackResponseBody extends Error {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: GetChargebackLinks | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetChargebackResponseBodyData;

  constructor(err: GetChargebackResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.status != null) this.status = err.status;
    if (err.title != null) this.title = err.title;
    if (err.detail != null) this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    if (err.links != null) this.links = err.links;

    this.name = "GetChargebackResponseBody";
  }
}

/** @internal */
export const GetChargebackDocumentation$inboundSchema: z.ZodType<
  GetChargebackDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.any(),
  type: z.any(),
});

/** @internal */
export type GetChargebackDocumentation$Outbound = {
  href?: any;
  type?: any;
};

/** @internal */
export const GetChargebackDocumentation$outboundSchema: z.ZodType<
  GetChargebackDocumentation$Outbound,
  z.ZodTypeDef,
  GetChargebackDocumentation
> = z.object({
  href: z.any(),
  type: z.any(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetChargebackDocumentation$ {
  /** @deprecated use `GetChargebackDocumentation$inboundSchema` instead. */
  export const inboundSchema = GetChargebackDocumentation$inboundSchema;
  /** @deprecated use `GetChargebackDocumentation$outboundSchema` instead. */
  export const outboundSchema = GetChargebackDocumentation$outboundSchema;
  /** @deprecated use `GetChargebackDocumentation$Outbound` instead. */
  export type Outbound = GetChargebackDocumentation$Outbound;
}

/** @internal */
export const GetChargebackLinks$inboundSchema: z.ZodType<
  GetChargebackLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  documentation: z.lazy(() => GetChargebackDocumentation$inboundSchema)
    .optional(),
});

/** @internal */
export type GetChargebackLinks$Outbound = {
  documentation?: GetChargebackDocumentation$Outbound | undefined;
};

/** @internal */
export const GetChargebackLinks$outboundSchema: z.ZodType<
  GetChargebackLinks$Outbound,
  z.ZodTypeDef,
  GetChargebackLinks
> = z.object({
  documentation: z.lazy(() => GetChargebackDocumentation$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetChargebackLinks$ {
  /** @deprecated use `GetChargebackLinks$inboundSchema` instead. */
  export const inboundSchema = GetChargebackLinks$inboundSchema;
  /** @deprecated use `GetChargebackLinks$outboundSchema` instead. */
  export const outboundSchema = GetChargebackLinks$outboundSchema;
  /** @deprecated use `GetChargebackLinks$Outbound` instead. */
  export type Outbound = GetChargebackLinks$Outbound;
}

/** @internal */
export const GetChargebackResponseBody$inboundSchema: z.ZodType<
  GetChargebackResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
  field: z.nullable(z.string()).optional(),
  _links: z.lazy(() => GetChargebackLinks$inboundSchema).optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new GetChargebackResponseBody(remapped);
  });

/** @internal */
export type GetChargebackResponseBody$Outbound = {
  status?: number | undefined;
  title?: string | undefined;
  detail?: string | undefined;
  field?: string | null | undefined;
  _links?: GetChargebackLinks$Outbound | undefined;
};

/** @internal */
export const GetChargebackResponseBody$outboundSchema: z.ZodType<
  GetChargebackResponseBody$Outbound,
  z.ZodTypeDef,
  GetChargebackResponseBody
> = z.instanceof(GetChargebackResponseBody)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int().optional(),
      title: z.string().optional(),
      detail: z.string().optional(),
      field: z.nullable(z.string()).optional(),
      links: z.lazy(() => GetChargebackLinks$outboundSchema).optional(),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetChargebackResponseBody$ {
  /** @deprecated use `GetChargebackResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetChargebackResponseBody$inboundSchema;
  /** @deprecated use `GetChargebackResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetChargebackResponseBody$outboundSchema;
  /** @deprecated use `GetChargebackResponseBody$Outbound` instead. */
  export type Outbound = GetChargebackResponseBody$Outbound;
}
