/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * The URL to the generic Mollie API error handling guide.
 */
export type GetPaymentDocumentation = {
  href?: any | undefined;
  type?: any | undefined;
};

export type GetPaymentLinks = {
  /**
   * The URL to the generic Mollie API error handling guide.
   */
  documentation?: GetPaymentDocumentation | undefined;
};

/**
 * An error response object.
 */
export type GetPaymentResponseBodyData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: GetPaymentLinks | undefined;
};

/**
 * An error response object.
 */
export class GetPaymentResponseBody extends Error {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: GetPaymentLinks | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetPaymentResponseBodyData;

  constructor(err: GetPaymentResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.status != null) this.status = err.status;
    if (err.title != null) this.title = err.title;
    if (err.detail != null) this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    if (err.links != null) this.links = err.links;

    this.name = "GetPaymentResponseBody";
  }
}

/** @internal */
export const GetPaymentDocumentation$inboundSchema: z.ZodType<
  GetPaymentDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.any(),
  type: z.any(),
});

/** @internal */
export type GetPaymentDocumentation$Outbound = {
  href?: any;
  type?: any;
};

/** @internal */
export const GetPaymentDocumentation$outboundSchema: z.ZodType<
  GetPaymentDocumentation$Outbound,
  z.ZodTypeDef,
  GetPaymentDocumentation
> = z.object({
  href: z.any(),
  type: z.any(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPaymentDocumentation$ {
  /** @deprecated use `GetPaymentDocumentation$inboundSchema` instead. */
  export const inboundSchema = GetPaymentDocumentation$inboundSchema;
  /** @deprecated use `GetPaymentDocumentation$outboundSchema` instead. */
  export const outboundSchema = GetPaymentDocumentation$outboundSchema;
  /** @deprecated use `GetPaymentDocumentation$Outbound` instead. */
  export type Outbound = GetPaymentDocumentation$Outbound;
}

/** @internal */
export const GetPaymentLinks$inboundSchema: z.ZodType<
  GetPaymentLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  documentation: z.lazy(() => GetPaymentDocumentation$inboundSchema).optional(),
});

/** @internal */
export type GetPaymentLinks$Outbound = {
  documentation?: GetPaymentDocumentation$Outbound | undefined;
};

/** @internal */
export const GetPaymentLinks$outboundSchema: z.ZodType<
  GetPaymentLinks$Outbound,
  z.ZodTypeDef,
  GetPaymentLinks
> = z.object({
  documentation: z.lazy(() => GetPaymentDocumentation$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPaymentLinks$ {
  /** @deprecated use `GetPaymentLinks$inboundSchema` instead. */
  export const inboundSchema = GetPaymentLinks$inboundSchema;
  /** @deprecated use `GetPaymentLinks$outboundSchema` instead. */
  export const outboundSchema = GetPaymentLinks$outboundSchema;
  /** @deprecated use `GetPaymentLinks$Outbound` instead. */
  export type Outbound = GetPaymentLinks$Outbound;
}

/** @internal */
export const GetPaymentResponseBody$inboundSchema: z.ZodType<
  GetPaymentResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
  field: z.nullable(z.string()).optional(),
  _links: z.lazy(() => GetPaymentLinks$inboundSchema).optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new GetPaymentResponseBody(remapped);
  });

/** @internal */
export type GetPaymentResponseBody$Outbound = {
  status?: number | undefined;
  title?: string | undefined;
  detail?: string | undefined;
  field?: string | null | undefined;
  _links?: GetPaymentLinks$Outbound | undefined;
};

/** @internal */
export const GetPaymentResponseBody$outboundSchema: z.ZodType<
  GetPaymentResponseBody$Outbound,
  z.ZodTypeDef,
  GetPaymentResponseBody
> = z.instanceof(GetPaymentResponseBody)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int().optional(),
      title: z.string().optional(),
      detail: z.string().optional(),
      field: z.nullable(z.string()).optional(),
      links: z.lazy(() => GetPaymentLinks$outboundSchema).optional(),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPaymentResponseBody$ {
  /** @deprecated use `GetPaymentResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetPaymentResponseBody$inboundSchema;
  /** @deprecated use `GetPaymentResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetPaymentResponseBody$outboundSchema;
  /** @deprecated use `GetPaymentResponseBody$Outbound` instead. */
  export type Outbound = GetPaymentResponseBody$Outbound;
}
