/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * The URL to the generic Mollie API error handling guide.
 */
export type GetRefundDocumentation = {
  href?: any | undefined;
  type?: any | undefined;
};

export type GetRefundLinks = {
  /**
   * The URL to the generic Mollie API error handling guide.
   */
  documentation?: GetRefundDocumentation | undefined;
};

/**
 * An error response object.
 */
export type GetRefundResponseBodyData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: GetRefundLinks | undefined;
};

/**
 * An error response object.
 */
export class GetRefundResponseBody extends Error {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: GetRefundLinks | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetRefundResponseBodyData;

  constructor(err: GetRefundResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.status != null) this.status = err.status;
    if (err.title != null) this.title = err.title;
    if (err.detail != null) this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    if (err.links != null) this.links = err.links;

    this.name = "GetRefundResponseBody";
  }
}

/** @internal */
export const GetRefundDocumentation$inboundSchema: z.ZodType<
  GetRefundDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.any(),
  type: z.any(),
});

/** @internal */
export type GetRefundDocumentation$Outbound = {
  href?: any;
  type?: any;
};

/** @internal */
export const GetRefundDocumentation$outboundSchema: z.ZodType<
  GetRefundDocumentation$Outbound,
  z.ZodTypeDef,
  GetRefundDocumentation
> = z.object({
  href: z.any(),
  type: z.any(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRefundDocumentation$ {
  /** @deprecated use `GetRefundDocumentation$inboundSchema` instead. */
  export const inboundSchema = GetRefundDocumentation$inboundSchema;
  /** @deprecated use `GetRefundDocumentation$outboundSchema` instead. */
  export const outboundSchema = GetRefundDocumentation$outboundSchema;
  /** @deprecated use `GetRefundDocumentation$Outbound` instead. */
  export type Outbound = GetRefundDocumentation$Outbound;
}

/** @internal */
export const GetRefundLinks$inboundSchema: z.ZodType<
  GetRefundLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  documentation: z.lazy(() => GetRefundDocumentation$inboundSchema).optional(),
});

/** @internal */
export type GetRefundLinks$Outbound = {
  documentation?: GetRefundDocumentation$Outbound | undefined;
};

/** @internal */
export const GetRefundLinks$outboundSchema: z.ZodType<
  GetRefundLinks$Outbound,
  z.ZodTypeDef,
  GetRefundLinks
> = z.object({
  documentation: z.lazy(() => GetRefundDocumentation$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRefundLinks$ {
  /** @deprecated use `GetRefundLinks$inboundSchema` instead. */
  export const inboundSchema = GetRefundLinks$inboundSchema;
  /** @deprecated use `GetRefundLinks$outboundSchema` instead. */
  export const outboundSchema = GetRefundLinks$outboundSchema;
  /** @deprecated use `GetRefundLinks$Outbound` instead. */
  export type Outbound = GetRefundLinks$Outbound;
}

/** @internal */
export const GetRefundResponseBody$inboundSchema: z.ZodType<
  GetRefundResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
  field: z.nullable(z.string()).optional(),
  _links: z.lazy(() => GetRefundLinks$inboundSchema).optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new GetRefundResponseBody(remapped);
  });

/** @internal */
export type GetRefundResponseBody$Outbound = {
  status?: number | undefined;
  title?: string | undefined;
  detail?: string | undefined;
  field?: string | null | undefined;
  _links?: GetRefundLinks$Outbound | undefined;
};

/** @internal */
export const GetRefundResponseBody$outboundSchema: z.ZodType<
  GetRefundResponseBody$Outbound,
  z.ZodTypeDef,
  GetRefundResponseBody
> = z.instanceof(GetRefundResponseBody)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int().optional(),
      title: z.string().optional(),
      detail: z.string().optional(),
      field: z.nullable(z.string()).optional(),
      links: z.lazy(() => GetRefundLinks$outboundSchema).optional(),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRefundResponseBody$ {
  /** @deprecated use `GetRefundResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetRefundResponseBody$inboundSchema;
  /** @deprecated use `GetRefundResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetRefundResponseBody$outboundSchema;
  /** @deprecated use `GetRefundResponseBody$Outbound` instead. */
  export type Outbound = GetRefundResponseBody$Outbound;
}
