/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * The URL to the generic Mollie API error handling guide.
 */
export type ListPaymentLinksDocumentation = {
  href?: any | undefined;
  type?: any | undefined;
};

export type ListPaymentLinksLinks = {
  /**
   * The URL to the generic Mollie API error handling guide.
   */
  documentation?: ListPaymentLinksDocumentation | undefined;
};

/**
 * An error response object.
 */
export type ListPaymentLinksResponseBodyData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: ListPaymentLinksLinks | undefined;
};

/**
 * An error response object.
 */
export class ListPaymentLinksResponseBody extends Error {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: ListPaymentLinksLinks | undefined;

  /** The original data that was passed to this error instance. */
  data$: ListPaymentLinksResponseBodyData;

  constructor(err: ListPaymentLinksResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.status != null) this.status = err.status;
    if (err.title != null) this.title = err.title;
    if (err.detail != null) this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    if (err.links != null) this.links = err.links;

    this.name = "ListPaymentLinksResponseBody";
  }
}

/** @internal */
export const ListPaymentLinksDocumentation$inboundSchema: z.ZodType<
  ListPaymentLinksDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.any(),
  type: z.any(),
});

/** @internal */
export type ListPaymentLinksDocumentation$Outbound = {
  href?: any;
  type?: any;
};

/** @internal */
export const ListPaymentLinksDocumentation$outboundSchema: z.ZodType<
  ListPaymentLinksDocumentation$Outbound,
  z.ZodTypeDef,
  ListPaymentLinksDocumentation
> = z.object({
  href: z.any(),
  type: z.any(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListPaymentLinksDocumentation$ {
  /** @deprecated use `ListPaymentLinksDocumentation$inboundSchema` instead. */
  export const inboundSchema = ListPaymentLinksDocumentation$inboundSchema;
  /** @deprecated use `ListPaymentLinksDocumentation$outboundSchema` instead. */
  export const outboundSchema = ListPaymentLinksDocumentation$outboundSchema;
  /** @deprecated use `ListPaymentLinksDocumentation$Outbound` instead. */
  export type Outbound = ListPaymentLinksDocumentation$Outbound;
}

/** @internal */
export const ListPaymentLinksLinks$inboundSchema: z.ZodType<
  ListPaymentLinksLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  documentation: z.lazy(() => ListPaymentLinksDocumentation$inboundSchema)
    .optional(),
});

/** @internal */
export type ListPaymentLinksLinks$Outbound = {
  documentation?: ListPaymentLinksDocumentation$Outbound | undefined;
};

/** @internal */
export const ListPaymentLinksLinks$outboundSchema: z.ZodType<
  ListPaymentLinksLinks$Outbound,
  z.ZodTypeDef,
  ListPaymentLinksLinks
> = z.object({
  documentation: z.lazy(() => ListPaymentLinksDocumentation$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListPaymentLinksLinks$ {
  /** @deprecated use `ListPaymentLinksLinks$inboundSchema` instead. */
  export const inboundSchema = ListPaymentLinksLinks$inboundSchema;
  /** @deprecated use `ListPaymentLinksLinks$outboundSchema` instead. */
  export const outboundSchema = ListPaymentLinksLinks$outboundSchema;
  /** @deprecated use `ListPaymentLinksLinks$Outbound` instead. */
  export type Outbound = ListPaymentLinksLinks$Outbound;
}

/** @internal */
export const ListPaymentLinksResponseBody$inboundSchema: z.ZodType<
  ListPaymentLinksResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
  field: z.nullable(z.string()).optional(),
  _links: z.lazy(() => ListPaymentLinksLinks$inboundSchema).optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new ListPaymentLinksResponseBody(remapped);
  });

/** @internal */
export type ListPaymentLinksResponseBody$Outbound = {
  status?: number | undefined;
  title?: string | undefined;
  detail?: string | undefined;
  field?: string | null | undefined;
  _links?: ListPaymentLinksLinks$Outbound | undefined;
};

/** @internal */
export const ListPaymentLinksResponseBody$outboundSchema: z.ZodType<
  ListPaymentLinksResponseBody$Outbound,
  z.ZodTypeDef,
  ListPaymentLinksResponseBody
> = z.instanceof(ListPaymentLinksResponseBody)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int().optional(),
      title: z.string().optional(),
      detail: z.string().optional(),
      field: z.nullable(z.string()).optional(),
      links: z.lazy(() => ListPaymentLinksLinks$outboundSchema).optional(),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListPaymentLinksResponseBody$ {
  /** @deprecated use `ListPaymentLinksResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListPaymentLinksResponseBody$inboundSchema;
  /** @deprecated use `ListPaymentLinksResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListPaymentLinksResponseBody$outboundSchema;
  /** @deprecated use `ListPaymentLinksResponseBody$Outbound` instead. */
  export type Outbound = ListPaymentLinksResponseBody$Outbound;
}
