/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * The URL to the generic Mollie API error handling guide.
 */
export type ListTerminalsDocumentation = {
  href?: any | undefined;
  type?: any | undefined;
};

export type ListTerminalsLinks = {
  /**
   * The URL to the generic Mollie API error handling guide.
   */
  documentation?: ListTerminalsDocumentation | undefined;
};

/**
 * An error response object.
 */
export type ListTerminalsResponseBodyData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: ListTerminalsLinks | undefined;
};

/**
 * An error response object.
 */
export class ListTerminalsResponseBody extends Error {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: ListTerminalsLinks | undefined;

  /** The original data that was passed to this error instance. */
  data$: ListTerminalsResponseBodyData;

  constructor(err: ListTerminalsResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.status != null) this.status = err.status;
    if (err.title != null) this.title = err.title;
    if (err.detail != null) this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    if (err.links != null) this.links = err.links;

    this.name = "ListTerminalsResponseBody";
  }
}

/** @internal */
export const ListTerminalsDocumentation$inboundSchema: z.ZodType<
  ListTerminalsDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.any(),
  type: z.any(),
});

/** @internal */
export type ListTerminalsDocumentation$Outbound = {
  href?: any;
  type?: any;
};

/** @internal */
export const ListTerminalsDocumentation$outboundSchema: z.ZodType<
  ListTerminalsDocumentation$Outbound,
  z.ZodTypeDef,
  ListTerminalsDocumentation
> = z.object({
  href: z.any(),
  type: z.any(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTerminalsDocumentation$ {
  /** @deprecated use `ListTerminalsDocumentation$inboundSchema` instead. */
  export const inboundSchema = ListTerminalsDocumentation$inboundSchema;
  /** @deprecated use `ListTerminalsDocumentation$outboundSchema` instead. */
  export const outboundSchema = ListTerminalsDocumentation$outboundSchema;
  /** @deprecated use `ListTerminalsDocumentation$Outbound` instead. */
  export type Outbound = ListTerminalsDocumentation$Outbound;
}

/** @internal */
export const ListTerminalsLinks$inboundSchema: z.ZodType<
  ListTerminalsLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  documentation: z.lazy(() => ListTerminalsDocumentation$inboundSchema)
    .optional(),
});

/** @internal */
export type ListTerminalsLinks$Outbound = {
  documentation?: ListTerminalsDocumentation$Outbound | undefined;
};

/** @internal */
export const ListTerminalsLinks$outboundSchema: z.ZodType<
  ListTerminalsLinks$Outbound,
  z.ZodTypeDef,
  ListTerminalsLinks
> = z.object({
  documentation: z.lazy(() => ListTerminalsDocumentation$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTerminalsLinks$ {
  /** @deprecated use `ListTerminalsLinks$inboundSchema` instead. */
  export const inboundSchema = ListTerminalsLinks$inboundSchema;
  /** @deprecated use `ListTerminalsLinks$outboundSchema` instead. */
  export const outboundSchema = ListTerminalsLinks$outboundSchema;
  /** @deprecated use `ListTerminalsLinks$Outbound` instead. */
  export type Outbound = ListTerminalsLinks$Outbound;
}

/** @internal */
export const ListTerminalsResponseBody$inboundSchema: z.ZodType<
  ListTerminalsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
  field: z.nullable(z.string()).optional(),
  _links: z.lazy(() => ListTerminalsLinks$inboundSchema).optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new ListTerminalsResponseBody(remapped);
  });

/** @internal */
export type ListTerminalsResponseBody$Outbound = {
  status?: number | undefined;
  title?: string | undefined;
  detail?: string | undefined;
  field?: string | null | undefined;
  _links?: ListTerminalsLinks$Outbound | undefined;
};

/** @internal */
export const ListTerminalsResponseBody$outboundSchema: z.ZodType<
  ListTerminalsResponseBody$Outbound,
  z.ZodTypeDef,
  ListTerminalsResponseBody
> = z.instanceof(ListTerminalsResponseBody)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int().optional(),
      title: z.string().optional(),
      detail: z.string().optional(),
      field: z.nullable(z.string()).optional(),
      links: z.lazy(() => ListTerminalsLinks$outboundSchema).optional(),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTerminalsResponseBody$ {
  /** @deprecated use `ListTerminalsResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListTerminalsResponseBody$inboundSchema;
  /** @deprecated use `ListTerminalsResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListTerminalsResponseBody$outboundSchema;
  /** @deprecated use `ListTerminalsResponseBody$Outbound` instead. */
  export type Outbound = ListTerminalsResponseBody$Outbound;
}
