/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * The URL to the generic Mollie API error handling guide.
 */
export type ListAllMethodsDocumentation = {
  href?: any | undefined;
  type?: any | undefined;
};

export type ListAllMethodsLinks = {
  /**
   * The URL to the generic Mollie API error handling guide.
   */
  documentation?: ListAllMethodsDocumentation | undefined;
};

/**
 * An error response object.
 */
export type ListAllMethodsResponseBodyData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: ListAllMethodsLinks | undefined;
};

/**
 * An error response object.
 */
export class ListAllMethodsResponseBody extends Error {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: ListAllMethodsLinks | undefined;

  /** The original data that was passed to this error instance. */
  data$: ListAllMethodsResponseBodyData;

  constructor(err: ListAllMethodsResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.status != null) this.status = err.status;
    if (err.title != null) this.title = err.title;
    if (err.detail != null) this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    if (err.links != null) this.links = err.links;

    this.name = "ListAllMethodsResponseBody";
  }
}

/** @internal */
export const ListAllMethodsDocumentation$inboundSchema: z.ZodType<
  ListAllMethodsDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.any(),
  type: z.any(),
});

/** @internal */
export type ListAllMethodsDocumentation$Outbound = {
  href?: any;
  type?: any;
};

/** @internal */
export const ListAllMethodsDocumentation$outboundSchema: z.ZodType<
  ListAllMethodsDocumentation$Outbound,
  z.ZodTypeDef,
  ListAllMethodsDocumentation
> = z.object({
  href: z.any(),
  type: z.any(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAllMethodsDocumentation$ {
  /** @deprecated use `ListAllMethodsDocumentation$inboundSchema` instead. */
  export const inboundSchema = ListAllMethodsDocumentation$inboundSchema;
  /** @deprecated use `ListAllMethodsDocumentation$outboundSchema` instead. */
  export const outboundSchema = ListAllMethodsDocumentation$outboundSchema;
  /** @deprecated use `ListAllMethodsDocumentation$Outbound` instead. */
  export type Outbound = ListAllMethodsDocumentation$Outbound;
}

/** @internal */
export const ListAllMethodsLinks$inboundSchema: z.ZodType<
  ListAllMethodsLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  documentation: z.lazy(() => ListAllMethodsDocumentation$inboundSchema)
    .optional(),
});

/** @internal */
export type ListAllMethodsLinks$Outbound = {
  documentation?: ListAllMethodsDocumentation$Outbound | undefined;
};

/** @internal */
export const ListAllMethodsLinks$outboundSchema: z.ZodType<
  ListAllMethodsLinks$Outbound,
  z.ZodTypeDef,
  ListAllMethodsLinks
> = z.object({
  documentation: z.lazy(() => ListAllMethodsDocumentation$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAllMethodsLinks$ {
  /** @deprecated use `ListAllMethodsLinks$inboundSchema` instead. */
  export const inboundSchema = ListAllMethodsLinks$inboundSchema;
  /** @deprecated use `ListAllMethodsLinks$outboundSchema` instead. */
  export const outboundSchema = ListAllMethodsLinks$outboundSchema;
  /** @deprecated use `ListAllMethodsLinks$Outbound` instead. */
  export type Outbound = ListAllMethodsLinks$Outbound;
}

/** @internal */
export const ListAllMethodsResponseBody$inboundSchema: z.ZodType<
  ListAllMethodsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
  field: z.nullable(z.string()).optional(),
  _links: z.lazy(() => ListAllMethodsLinks$inboundSchema).optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new ListAllMethodsResponseBody(remapped);
  });

/** @internal */
export type ListAllMethodsResponseBody$Outbound = {
  status?: number | undefined;
  title?: string | undefined;
  detail?: string | undefined;
  field?: string | null | undefined;
  _links?: ListAllMethodsLinks$Outbound | undefined;
};

/** @internal */
export const ListAllMethodsResponseBody$outboundSchema: z.ZodType<
  ListAllMethodsResponseBody$Outbound,
  z.ZodTypeDef,
  ListAllMethodsResponseBody
> = z.instanceof(ListAllMethodsResponseBody)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int().optional(),
      title: z.string().optional(),
      detail: z.string().optional(),
      field: z.nullable(z.string()).optional(),
      links: z.lazy(() => ListAllMethodsLinks$outboundSchema).optional(),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAllMethodsResponseBody$ {
  /** @deprecated use `ListAllMethodsResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListAllMethodsResponseBody$inboundSchema;
  /** @deprecated use `ListAllMethodsResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListAllMethodsResponseBody$outboundSchema;
  /** @deprecated use `ListAllMethodsResponseBody$Outbound` instead. */
  export type Outbound = ListAllMethodsResponseBody$Outbound;
}
