/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * The URL to the generic Mollie API error handling guide.
 */
export type ListPaymentsDocumentation = {
  href?: any | undefined;
  type?: any | undefined;
};

export type ListPaymentsLinks = {
  /**
   * The URL to the generic Mollie API error handling guide.
   */
  documentation?: ListPaymentsDocumentation | undefined;
};

/**
 * An error response object.
 */
export type ListPaymentsResponseBodyData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: ListPaymentsLinks | undefined;
};

/**
 * An error response object.
 */
export class ListPaymentsResponseBody extends Error {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status?: number | undefined;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title?: string | undefined;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail?: string | undefined;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | null | undefined;
  links?: ListPaymentsLinks | undefined;

  /** The original data that was passed to this error instance. */
  data$: ListPaymentsResponseBodyData;

  constructor(err: ListPaymentsResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.status != null) this.status = err.status;
    if (err.title != null) this.title = err.title;
    if (err.detail != null) this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    if (err.links != null) this.links = err.links;

    this.name = "ListPaymentsResponseBody";
  }
}

/** @internal */
export const ListPaymentsDocumentation$inboundSchema: z.ZodType<
  ListPaymentsDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.any(),
  type: z.any(),
});

/** @internal */
export type ListPaymentsDocumentation$Outbound = {
  href?: any;
  type?: any;
};

/** @internal */
export const ListPaymentsDocumentation$outboundSchema: z.ZodType<
  ListPaymentsDocumentation$Outbound,
  z.ZodTypeDef,
  ListPaymentsDocumentation
> = z.object({
  href: z.any(),
  type: z.any(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListPaymentsDocumentation$ {
  /** @deprecated use `ListPaymentsDocumentation$inboundSchema` instead. */
  export const inboundSchema = ListPaymentsDocumentation$inboundSchema;
  /** @deprecated use `ListPaymentsDocumentation$outboundSchema` instead. */
  export const outboundSchema = ListPaymentsDocumentation$outboundSchema;
  /** @deprecated use `ListPaymentsDocumentation$Outbound` instead. */
  export type Outbound = ListPaymentsDocumentation$Outbound;
}

/** @internal */
export const ListPaymentsLinks$inboundSchema: z.ZodType<
  ListPaymentsLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  documentation: z.lazy(() => ListPaymentsDocumentation$inboundSchema)
    .optional(),
});

/** @internal */
export type ListPaymentsLinks$Outbound = {
  documentation?: ListPaymentsDocumentation$Outbound | undefined;
};

/** @internal */
export const ListPaymentsLinks$outboundSchema: z.ZodType<
  ListPaymentsLinks$Outbound,
  z.ZodTypeDef,
  ListPaymentsLinks
> = z.object({
  documentation: z.lazy(() => ListPaymentsDocumentation$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListPaymentsLinks$ {
  /** @deprecated use `ListPaymentsLinks$inboundSchema` instead. */
  export const inboundSchema = ListPaymentsLinks$inboundSchema;
  /** @deprecated use `ListPaymentsLinks$outboundSchema` instead. */
  export const outboundSchema = ListPaymentsLinks$outboundSchema;
  /** @deprecated use `ListPaymentsLinks$Outbound` instead. */
  export type Outbound = ListPaymentsLinks$Outbound;
}

/** @internal */
export const ListPaymentsResponseBody$inboundSchema: z.ZodType<
  ListPaymentsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
  field: z.nullable(z.string()).optional(),
  _links: z.lazy(() => ListPaymentsLinks$inboundSchema).optional(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new ListPaymentsResponseBody(remapped);
  });

/** @internal */
export type ListPaymentsResponseBody$Outbound = {
  status?: number | undefined;
  title?: string | undefined;
  detail?: string | undefined;
  field?: string | null | undefined;
  _links?: ListPaymentsLinks$Outbound | undefined;
};

/** @internal */
export const ListPaymentsResponseBody$outboundSchema: z.ZodType<
  ListPaymentsResponseBody$Outbound,
  z.ZodTypeDef,
  ListPaymentsResponseBody
> = z.instanceof(ListPaymentsResponseBody)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int().optional(),
      title: z.string().optional(),
      detail: z.string().optional(),
      field: z.nullable(z.string()).optional(),
      links: z.lazy(() => ListPaymentsLinks$outboundSchema).optional(),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListPaymentsResponseBody$ {
  /** @deprecated use `ListPaymentsResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListPaymentsResponseBody$inboundSchema;
  /** @deprecated use `ListPaymentsResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListPaymentsResponseBody$outboundSchema;
  /** @deprecated use `ListPaymentsResponseBody$Outbound` instead. */
  export type Outbound = ListPaymentsResponseBody$Outbound;
}
