/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CancelPaymentRequest = {
  /**
   * Provide the ID of the item you want to perform this operation on.
   */
  id: string;
  /**
   * Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting the `testmode` query parameter to `true`.
   *
   * @remarks
   *
   * Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
   */
  testmode?: boolean | null | undefined;
};

/** @internal */
export const CancelPaymentRequest$inboundSchema: z.ZodType<
  CancelPaymentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  testmode: z.nullable(z.boolean().default(false)),
});

/** @internal */
export type CancelPaymentRequest$Outbound = {
  id: string;
  testmode: boolean | null;
};

/** @internal */
export const CancelPaymentRequest$outboundSchema: z.ZodType<
  CancelPaymentRequest$Outbound,
  z.ZodTypeDef,
  CancelPaymentRequest
> = z.object({
  id: z.string(),
  testmode: z.nullable(z.boolean().default(false)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CancelPaymentRequest$ {
  /** @deprecated use `CancelPaymentRequest$inboundSchema` instead. */
  export const inboundSchema = CancelPaymentRequest$inboundSchema;
  /** @deprecated use `CancelPaymentRequest$outboundSchema` instead. */
  export const outboundSchema = CancelPaymentRequest$outboundSchema;
  /** @deprecated use `CancelPaymentRequest$Outbound` instead. */
  export type Outbound = CancelPaymentRequest$Outbound;
}
