/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetTerminalRequest = {
  /**
   * Provide the ID of the item you want to perform this operation on.
   */
  id: string;
  /**
   * Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting the `testmode` query parameter to `true`.
   *
   * @remarks
   *
   * Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
   */
  testmode?: boolean | null | undefined;
};

/**
 * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
 */
export type GetTerminalSelf = {
  /**
   * The actual URL string.
   */
  href?: string | undefined;
  /**
   * The content type of the page or endpoint the URL points to.
   */
  type?: string | undefined;
};

/**
 * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
 */
export type GetTerminalDocumentation = {
  /**
   * The actual URL string.
   */
  href?: string | undefined;
  /**
   * The content type of the page or endpoint the URL points to.
   */
  type?: string | undefined;
};

/**
 * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
 */
export type GetTerminalLinks = {
  /**
   * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
   */
  self?: GetTerminalSelf | undefined;
  /**
   * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
   */
  documentation?: GetTerminalDocumentation | undefined;
};

/**
 * The terminal object.
 */
export type GetTerminalResponseBody = {
  /**
   * Indicates the response contains a terminal object. Will always contain the string `terminal` for this endpoint.
   */
  resource?: string | undefined;
  /**
   * The identifier uniquely referring to this terminal. Example: `term_7MgL4wea46qkRcoTZjWEH`.
   */
  id?: string | undefined;
  /**
   * A short description of the terminal. The description can be used as an identifier for the terminal. Currently, the description is set when the terminal is initially configured. It will be visible in the Mollie Dashboard, and it may be visible on the device itself depending on the device.
   */
  description?: string | undefined;
  /**
   * The status of the terminal:
   *
   * @remarks
   *
   * * `pending`: The device has been linked to your account, but has not yet been activated. If you ordered a terminal from us, it may already become visible in your account with this status.
   * * `active`: The terminal is fully configured and ready to accept payments.
   * * `inactive`: The terminal has been deactivated. Deactivation happens for example if you returned the device to Mollie, or if you requested to move it to another profile or organization.
   */
  status?: string | undefined;
  /**
   * The brand of the terminal. For example, `PAX`.
   */
  brand?: string | null | undefined;
  /**
   * The model of the terminal. For example for a PAX A920, this field's value will be `A920`.
   */
  model?: string | null | undefined;
  /**
   * The serial number of the terminal. The serial number is provided at terminal creation time.
   */
  serialNumber?: string | null | undefined;
  /**
   * The currency configured on the terminal, in ISO 4217 format. Currently most of our terminals are bound to a specific currency, chosen during setup.
   */
  currency?: string | null | undefined;
  /**
   * The identifier referring to the [profile](get-profile) this entity belongs to.
   *
   * @remarks
   *
   * Most API credentials are linked to a single profile. In these cases the `profileId` can be omitted in the creation request. For organization-level credentials such as OAuth access tokens however, the `profileId` parameter is required.
   */
  profileId?: string | null | undefined;
  /**
   * The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
   */
  createdAt?: string | undefined;
  /**
   * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
   */
  links?: GetTerminalLinks | undefined;
};

/** @internal */
export const GetTerminalRequest$inboundSchema: z.ZodType<
  GetTerminalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  testmode: z.nullable(z.boolean().default(false)),
});

/** @internal */
export type GetTerminalRequest$Outbound = {
  id: string;
  testmode: boolean | null;
};

/** @internal */
export const GetTerminalRequest$outboundSchema: z.ZodType<
  GetTerminalRequest$Outbound,
  z.ZodTypeDef,
  GetTerminalRequest
> = z.object({
  id: z.string(),
  testmode: z.nullable(z.boolean().default(false)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTerminalRequest$ {
  /** @deprecated use `GetTerminalRequest$inboundSchema` instead. */
  export const inboundSchema = GetTerminalRequest$inboundSchema;
  /** @deprecated use `GetTerminalRequest$outboundSchema` instead. */
  export const outboundSchema = GetTerminalRequest$outboundSchema;
  /** @deprecated use `GetTerminalRequest$Outbound` instead. */
  export type Outbound = GetTerminalRequest$Outbound;
}

/** @internal */
export const GetTerminalSelf$inboundSchema: z.ZodType<
  GetTerminalSelf,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string().optional(),
  type: z.string().optional(),
});

/** @internal */
export type GetTerminalSelf$Outbound = {
  href?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const GetTerminalSelf$outboundSchema: z.ZodType<
  GetTerminalSelf$Outbound,
  z.ZodTypeDef,
  GetTerminalSelf
> = z.object({
  href: z.string().optional(),
  type: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTerminalSelf$ {
  /** @deprecated use `GetTerminalSelf$inboundSchema` instead. */
  export const inboundSchema = GetTerminalSelf$inboundSchema;
  /** @deprecated use `GetTerminalSelf$outboundSchema` instead. */
  export const outboundSchema = GetTerminalSelf$outboundSchema;
  /** @deprecated use `GetTerminalSelf$Outbound` instead. */
  export type Outbound = GetTerminalSelf$Outbound;
}

/** @internal */
export const GetTerminalDocumentation$inboundSchema: z.ZodType<
  GetTerminalDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string().optional(),
  type: z.string().optional(),
});

/** @internal */
export type GetTerminalDocumentation$Outbound = {
  href?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const GetTerminalDocumentation$outboundSchema: z.ZodType<
  GetTerminalDocumentation$Outbound,
  z.ZodTypeDef,
  GetTerminalDocumentation
> = z.object({
  href: z.string().optional(),
  type: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTerminalDocumentation$ {
  /** @deprecated use `GetTerminalDocumentation$inboundSchema` instead. */
  export const inboundSchema = GetTerminalDocumentation$inboundSchema;
  /** @deprecated use `GetTerminalDocumentation$outboundSchema` instead. */
  export const outboundSchema = GetTerminalDocumentation$outboundSchema;
  /** @deprecated use `GetTerminalDocumentation$Outbound` instead. */
  export type Outbound = GetTerminalDocumentation$Outbound;
}

/** @internal */
export const GetTerminalLinks$inboundSchema: z.ZodType<
  GetTerminalLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.lazy(() => GetTerminalSelf$inboundSchema).optional(),
  documentation: z.lazy(() => GetTerminalDocumentation$inboundSchema)
    .optional(),
});

/** @internal */
export type GetTerminalLinks$Outbound = {
  self?: GetTerminalSelf$Outbound | undefined;
  documentation?: GetTerminalDocumentation$Outbound | undefined;
};

/** @internal */
export const GetTerminalLinks$outboundSchema: z.ZodType<
  GetTerminalLinks$Outbound,
  z.ZodTypeDef,
  GetTerminalLinks
> = z.object({
  self: z.lazy(() => GetTerminalSelf$outboundSchema).optional(),
  documentation: z.lazy(() => GetTerminalDocumentation$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTerminalLinks$ {
  /** @deprecated use `GetTerminalLinks$inboundSchema` instead. */
  export const inboundSchema = GetTerminalLinks$inboundSchema;
  /** @deprecated use `GetTerminalLinks$outboundSchema` instead. */
  export const outboundSchema = GetTerminalLinks$outboundSchema;
  /** @deprecated use `GetTerminalLinks$Outbound` instead. */
  export type Outbound = GetTerminalLinks$Outbound;
}

/** @internal */
export const GetTerminalResponseBody$inboundSchema: z.ZodType<
  GetTerminalResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource: z.string().default("terminal"),
  id: z.string().optional(),
  description: z.string().optional(),
  status: z.string().optional(),
  brand: z.nullable(z.string()).optional(),
  model: z.nullable(z.string()).optional(),
  serialNumber: z.nullable(z.string()).optional(),
  currency: z.nullable(z.string()).optional(),
  profileId: z.nullable(z.string()).optional(),
  createdAt: z.string().optional(),
  _links: z.lazy(() => GetTerminalLinks$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
  });
});

/** @internal */
export type GetTerminalResponseBody$Outbound = {
  resource: string;
  id?: string | undefined;
  description?: string | undefined;
  status?: string | undefined;
  brand?: string | null | undefined;
  model?: string | null | undefined;
  serialNumber?: string | null | undefined;
  currency?: string | null | undefined;
  profileId?: string | null | undefined;
  createdAt?: string | undefined;
  _links?: GetTerminalLinks$Outbound | undefined;
};

/** @internal */
export const GetTerminalResponseBody$outboundSchema: z.ZodType<
  GetTerminalResponseBody$Outbound,
  z.ZodTypeDef,
  GetTerminalResponseBody
> = z.object({
  resource: z.string().default("terminal"),
  id: z.string().optional(),
  description: z.string().optional(),
  status: z.string().optional(),
  brand: z.nullable(z.string()).optional(),
  model: z.nullable(z.string()).optional(),
  serialNumber: z.nullable(z.string()).optional(),
  currency: z.nullable(z.string()).optional(),
  profileId: z.nullable(z.string()).optional(),
  createdAt: z.string().optional(),
  links: z.lazy(() => GetTerminalLinks$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    links: "_links",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTerminalResponseBody$ {
  /** @deprecated use `GetTerminalResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetTerminalResponseBody$inboundSchema;
  /** @deprecated use `GetTerminalResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetTerminalResponseBody$outboundSchema;
  /** @deprecated use `GetTerminalResponseBody$Outbound` instead. */
  export type Outbound = GetTerminalResponseBody$Outbound;
}
